### ISSUE TITLE
Update App themes topic

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/app-builder-docfx#2]
Update this topic for App Themes:

https://www.infragistics.com/products/indigo-design/help/appbuilder/app-themes/app-themes

New content is available in [internal docs](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EXwOwXip-DhHv_4urC02vH0BFV1S2iGeu1BH5--DCyPZyA?e=JmbtNK&isSPOFile=1&CID=373D82AF-7C86-4897-A1E6-A1D7EFB83A91&wdLOR=c2E7B7E6D-F72D-434B-8EB7-53268068AB47).

**Comment by hanastasov** [comment]
Check if following topics should exist in JP version as well:

 0  en/appbuilder/using-data-in-your-app/binding-data-to-components.md 
Viewed
 0  en/appbuilder/using-data-in-your-app/data-sources.md

**Comment by zdrawku** [comment]
@Svetloslav15 could you please cherry pick your changes to vNext as well:

https://github.com/IgniteUI/app-builder-docfx/pull/3

**Comment by Svetloslav15** [comment]
@zdrawku I can't see vNext branch for this repo, should I create one?

**Comment by zdrawku** [comment]
Here it is https://github.com/IgniteUI/app-builder-docfx/tree/vNext

**Comment by Svetloslav15** [comment]
Done ✔️
