### ISSUE TITLE
Swagger Support topic enhacements

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/app-builder-docfx#94]
Questions from our customers:

- why my OpenAPI definitiion file is not supported
- why certain endpoints appear as greyed out
- offline version of AppBuilder / "I wonder if there is any on prem version of App Builder that we can use which will not hit so many external / internet URLs."

Answer these in the official documenation topic at [port](https://www.infragistics.com/products/appbuilder/help/open-api-swagger-support)

**Comment by zdrawku** [comment]
These points will be addressed with PR
https://github.com/IgniteUI/app-builder-docfx/pull/103
